# Generated by Django 4.0.3 on 2022-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Satzscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=7, max_digits=10)),
                ('satz', models.CharField(max_length=120)),
            ],
        ),
    ]
