# Generated by Django 4.0.3 on 2022-04-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_satzscore_session_id_satzscore_zeit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='satzscore',
            old_name='satz',
            new_name='target_satz',
        ),
        migrations.AddField(
            model_name='satzscore',
            name='at_ipa',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satzscore',
            name='google_ipa',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satzscore',
            name='google_transcript',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satzscore',
            name='ibm_ipa',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satzscore',
            name='ibm_transcript',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satzscore',
            name='target_ipa',
            field=models.TextField(default='.'),
            preserve_default=False,
        ),
    ]
